// Build the spoken intro text that is prepended to an episode so David can
// identify which queued episode is playing within the first ~2 seconds.
//
// The format is: "This is {show}. {title}. This episode is about {summary}."
// The "This is {show}. {title}." part comes from Pocket Casts metadata and
// ALWAYS works - it needs no model. The "This episode is about ..." sentence is
// generated by the local LLM from the episode transcript. If the transcript is
// missing, or the LLM call fails for any reason, we ship metadata-only. Episode
// identification must never depend on a working model.
//
// The LLM is reached through an injected fetch so unit tests never touch the
// real LM Studio endpoint.

const LMSTUDIO_URL = "http://localhost:1234/v1/chat/completions";
const LMSTUDIO_MODEL = "google/gemma-4-12b-qat";
const LMSTUDIO_TIMEOUT_MS = 30 * 1000;

// JSON schema we force the model to answer with. Strict so the response is a
// single short summary string we can drop straight into the sentence.
const SUMMARY_SCHEMA = {
  type: "json_schema",
  json_schema: {
    name: "episode_summary",
    strict: true,
    schema: {
      type: "object",
      properties: {
        summary: { type: "string" },
      },
      required: ["summary"],
      additionalProperties: false,
    },
  },
};

// Characters the TTS engine mispronounces or stumbles over. Em dash, en dash
// and non-breaking hyphen all read badly, so we strip them from the final text.
// (House style is " - " space-hyphen-space anyway, so dashes should not be here.)
function stripTtsUnfriendly(text) {
  if (!text) return "";
  return String(text)
    .replace(/[—–‑]/g, " ") // em dash, en dash, non-breaking hyphen
    .replace(/\s+/g, " ")
    .trim();
}

// Collapse whitespace and trim. Used to keep show/title metadata tidy without
// dropping the meaning - we never substitute the wrong title.
function sanitise(value) {
  if (value == null) return "";
  return String(value).replace(/\s+/g, " ").trim();
}

// Turn the transcript into a compact prompt body. We only need enough text for
// the model to summarise; cap it so a very long transcript does not blow the
// context window.
function transcriptToText(transcript, maxChars = 6000) {
  if (!transcript) return "";
  let text = "";
  if (typeof transcript === "string") {
    text = transcript;
  } else if (Array.isArray(transcript.segments)) {
    text = transcript.segments.map((s) => (s && s.text ? s.text : "")).join(" ");
  }
  text = sanitise(text);
  return text.length > maxChars ? text.slice(0, maxChars) : text;
}

// Pull the summary string out of an LM Studio chat completion. Reasoning builds
// leave message.content empty and put the answer in message.reasoning_content,
// so fall back to that. Returns "" if nothing usable is found.
function extractSummary(data) {
  const message = data && data.choices && data.choices[0] && data.choices[0].message;
  if (!message) return "";
  const raw = (message.content && String(message.content).trim())
    || (message.reasoning_content && String(message.reasoning_content).trim())
    || "";
  if (!raw) return "";

  // The strict json_schema means the content should be JSON like {"summary": "..."}.
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.summary === "string") return parsed.summary.trim();
  } catch {
    // Reasoning builds sometimes wrap or precede the JSON with prose. Try to dig
    // a summary out of an embedded JSON object before giving up.
    const m = /\{[\s\S]*"summary"[\s\S]*\}/.exec(raw);
    if (m) {
      try {
        const parsed = JSON.parse(m[0]);
        if (parsed && typeof parsed.summary === "string") return parsed.summary.trim();
      } catch {}
    }
  }
  return "";
}

// Ask the local LLM for a one-or-two-sentence summary of the episode. Degrades
// safely: any error, timeout, missing endpoint or empty answer resolves to "",
// never throws into the pipeline.
async function summariseTranscript({
  show, title, transcript,
  fetch,
  url = LMSTUDIO_URL,
  model = LMSTUDIO_MODEL,
  timeoutMs = LMSTUDIO_TIMEOUT_MS,
  signal,
} = {}) {
  if (typeof fetch !== "function") return "";
  const text = transcriptToText(transcript);
  if (!text) return "";

  const controller = typeof AbortController === "function" ? new AbortController() : null;
  let timer = null;
  if (controller) {
    timer = setTimeout(() => { try { controller.abort(); } catch {} }, timeoutMs);
    if (signal) {
      if (signal.aborted) { try { controller.abort(); } catch {} }
      else signal.addEventListener("abort", () => { try { controller.abort(); } catch {} }, { once: true });
    }
  }

  const body = {
    model,
    temperature: 0,
    max_tokens: 200,
    response_format: SUMMARY_SCHEMA,
    messages: [
      {
        role: "system",
        content:
          "You write the topic of a podcast episode as a short phrase (under 35 words) "
          + "that completes the sentence \"This episode is about ...\". Be concrete about the "
          + "actual topic. Do NOT begin with \"This episode\", \"In this episode\" or \"Today\" - "
          + "start straight at the topic. Reply only with the JSON object.",
      },
      {
        role: "user",
        content:
          `Podcast: ${sanitise(show) || "unknown"}\n`
          + `Episode title: ${sanitise(title) || "unknown"}\n\n`
          + `Transcript excerpt:\n${text}`,
      },
    ],
  };

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: controller ? controller.signal : undefined,
    });
    if (!res || !res.ok) return "";
    const data = await res.json();
    return stripTtsUnfriendly(extractSummary(data));
  } catch {
    return "";
  } finally {
    if (timer) clearTimeout(timer);
  }
}

// Build the full intro string. Metadata is always produced; the summary sentence
// is appended only when a transcript is present and the LLM call succeeds.
async function buildAnnouncementText({
  show, title, transcript, llm,
} = {}) {
  const cleanShow = sanitise(show);
  const cleanTitle = sanitise(title);

  const parts = [];
  if (cleanShow) parts.push(`This is ${cleanShow}.`);
  // Only add a full stop when the title does not already end in terminal
  // punctuation, so a title like "Who Won?" does not become "Who Won?.".
  if (cleanTitle) parts.push(/[.!?]$/.test(cleanTitle) ? cleanTitle : `${cleanTitle}.`);
  let metadata = parts.join(" ");

  let summary = "";
  if (transcript && llm && typeof llm.fetch === "function") {
    summary = await summariseTranscript({ show: cleanShow, title: cleanTitle, transcript, ...llm });
  }

  let full = metadata;
  if (summary) {
    // Strip any trailing punctuation/whitespace so we never double up the stop.
    const sentenceBody = summary.replace(/[\s.!?]+$/, "");
    // The model is asked for a bare topic phrase to slot into "This episode is
    // about ...". When it instead returns a full sentence that already opens
    // with "This episode" / "In this episode" / "Today" / "The episode", using
    // the lead-in would stutter ("...is about This episode investigates..."), so
    // we drop the lead-in and use the model's sentence as-is.
    const alreadyAClause = /^((in|on)\s+)?(this|today'?s?|the)\s+(episode|podcast|show|week|conversation)\b/i.test(sentenceBody)
      || /^today\b/i.test(sentenceBody);
    if (alreadyAClause) {
      const standalone = sentenceBody.charAt(0).toUpperCase() + sentenceBody.slice(1);
      full = `${metadata} ${standalone}.`.trim();
    } else {
      full = `${metadata} This episode is about ${sentenceBody}.`.trim();
    }
  }

  full = stripTtsUnfriendly(full);
  return full;
}

module.exports = {
  buildAnnouncementText,
  summariseTranscript,
  extractSummary,
  stripTtsUnfriendly,
  sanitise,
  transcriptToText,
  LMSTUDIO_URL,
  LMSTUDIO_MODEL,
  SUMMARY_SCHEMA,
};
