// Build the spoken intro text that is prepended to an episode so David can
// identify which queued episode is playing within the first ~2 seconds.
//
// The format is:
//   "This is {Show}. Episode {N}. {Title}. Published on the {Nth of Month YYYY}.
//    This episode is about {summary}."
// Everything except the summary comes straight from Pocket Casts metadata and
// ALWAYS works - it needs no model. The episode/season number and the publish
// date are derived DETERMINISTICALLY and are spoken only when the feed provides
// them (numbered shows give episode/season; narrative shows do not). The "This
// episode is about ..." sentence is generated by the local LLM from the episode
// transcript. If the transcript is missing, or the LLM call fails for any reason,
// we ship metadata-only. Episode identification must never depend on a working
// model.
//
// The LLM is reached through an injected fetch so unit tests never touch the
// real LM Studio endpoint.

const LMSTUDIO_URL = "http://localhost:1234/v1/chat/completions";
const LMSTUDIO_MODEL = "google/gemma-4-12b-qat";
const LMSTUDIO_TIMEOUT_MS = 30 * 1000;

// JSON schema we force the model to answer with. Strict so the response is a
// single short summary string we can drop straight into the sentence.
const SUMMARY_SCHEMA = {
  type: "json_schema",
  json_schema: {
    name: "episode_summary",
    strict: true,
    schema: {
      type: "object",
      properties: {
        summary: { type: "string" },
      },
      required: ["summary"],
      additionalProperties: false,
    },
  },
};

// Characters the TTS engine mispronounces or stumbles over. Em dash, en dash
// and non-breaking hyphen all read badly, so we strip them from the final text.
// (House style is " - " space-hyphen-space anyway, so dashes should not be here.)
function stripTtsUnfriendly(text) {
  if (!text) return "";
  return String(text)
    .replace(/[—–‑]/g, " ") // em dash, en dash, non-breaking hyphen
    .replace(/\s+/g, " ")
    .trim();
}

// Collapse whitespace and trim. Used to keep show/title metadata tidy without
// dropping the meaning - we never substitute the wrong title.
function sanitise(value) {
  if (value == null) return "";
  return String(value).replace(/\s+/g, " ").trim();
}

// Coerce a feed-supplied episode/season number to a positive integer, or null.
// Pocket Casts sometimes sends a numeric string ("47") or 0/"" for "no number";
// we only ever speak a real, positive whole number.
function toPositiveInt(value) {
  if (value == null) return null;
  const n = typeof value === "number" ? value : parseInt(String(value).trim(), 10);
  if (!Number.isFinite(n) || n <= 0 || Math.floor(n) !== n) return null;
  return n;
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

// Speak a day-of-month as an ordinal ("1st", "2nd", "3rd", "10th", "21st",
// "23rd"). The 11th/12th/13th are always "th" despite ending in 1/2/3.
function ordinal(day) {
  const tens = day % 100;
  if (tens >= 11 && tens <= 13) return `${day}th`;
  switch (day % 10) {
    case 1: return `${day}st`;
    case 2: return `${day}nd`;
    case 3: return `${day}rd`;
    default: return `${day}th`;
  }
}

// Turn a raw publish value (ISO string from ep.published) into a SPEECH date
// like "the 10th of June 2025", or "" when it is missing/unparseable. We read
// UTC date components so a midnight-UTC timestamp does not drift to the previous
// day in a local timezone. Never an ISO/numeric/slashed date.
function formatSpokenDate(published) {
  if (published == null || published === "") return "";
  const d = new Date(published);
  if (Number.isNaN(d.getTime())) return "";
  const day = d.getUTCDate();
  const month = MONTH_NAMES[d.getUTCMonth()];
  const year = d.getUTCFullYear();
  if (!month) return "";
  return `the ${ordinal(day)} of ${month} ${year}`;
}

// Build the spoken episode/season clause for the metadata line, or "" when there
// is no episode number. Format for SPEECH, never "S03E07": "Episode 47", or
// "Season 3, episode 7" when a season number is also present. A season with no
// episode number yields nothing (the episode number is what identifies the ep).
function formatEpisodeClause(episodeNumber, seasonNumber) {
  const ep = toPositiveInt(episodeNumber);
  if (ep == null) return "";
  const season = toPositiveInt(seasonNumber);
  if (season != null) return `Season ${season}, episode ${ep}.`;
  return `Episode ${ep}.`;
}

// Turn the transcript into a compact prompt body. We only need enough text for
// the model to summarise; cap it so a very long transcript does not blow the
// context window.
function transcriptToText(transcript, maxChars = 6000) {
  if (!transcript) return "";
  let text = "";
  if (typeof transcript === "string") {
    text = transcript;
  } else if (Array.isArray(transcript.segments)) {
    text = transcript.segments.map((s) => (s && s.text ? s.text : "")).join(" ");
  }
  text = sanitise(text);
  return text.length > maxChars ? text.slice(0, maxChars) : text;
}

// Pull the summary string out of an LM Studio chat completion. Reasoning builds
// leave message.content empty and put the answer in message.reasoning_content,
// so fall back to that. Returns "" if nothing usable is found.
function extractSummary(data) {
  const message = data && data.choices && data.choices[0] && data.choices[0].message;
  if (!message) return "";
  const raw = (message.content && String(message.content).trim())
    || (message.reasoning_content && String(message.reasoning_content).trim())
    || "";
  if (!raw) return "";

  // The strict json_schema means the content should be JSON like {"summary": "..."}.
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.summary === "string") return parsed.summary.trim();
  } catch {
    // Reasoning builds sometimes wrap or precede the JSON with prose. Try to dig
    // a summary out of an embedded JSON object before giving up.
    const m = /\{[\s\S]*"summary"[\s\S]*\}/.exec(raw);
    if (m) {
      try {
        const parsed = JSON.parse(m[0]);
        if (parsed && typeof parsed.summary === "string") return parsed.summary.trim();
      } catch {}
    }
  }
  return "";
}

// Ask the local LLM for a one-or-two-sentence summary of the episode. Degrades
// safely: any error, timeout, missing endpoint or empty answer resolves to "",
// never throws into the pipeline.
async function summariseTranscript({
  show, title, transcript,
  fetch,
  url = LMSTUDIO_URL,
  model = LMSTUDIO_MODEL,
  timeoutMs = LMSTUDIO_TIMEOUT_MS,
  signal,
} = {}) {
  if (typeof fetch !== "function") return "";
  const text = transcriptToText(transcript);
  if (!text) return "";

  const controller = typeof AbortController === "function" ? new AbortController() : null;
  let timer = null;
  if (controller) {
    timer = setTimeout(() => { try { controller.abort(); } catch {} }, timeoutMs);
    if (signal) {
      if (signal.aborted) { try { controller.abort(); } catch {} }
      else signal.addEventListener("abort", () => { try { controller.abort(); } catch {} }, { once: true });
    }
  }

  const body = {
    model,
    temperature: 0,
    max_tokens: 200,
    response_format: SUMMARY_SCHEMA,
    messages: [
      {
        role: "system",
        content:
          "You write the topic of a podcast episode as a short phrase (under 35 words) "
          + "that completes the sentence \"This episode is about ...\". Be concrete about the "
          + "actual topic. Do NOT begin with \"This episode\", \"In this episode\" or \"Today\" - "
          + "start straight at the topic. Reply only with the JSON object.",
      },
      {
        role: "user",
        content:
          `Podcast: ${sanitise(show) || "unknown"}\n`
          + `Episode title: ${sanitise(title) || "unknown"}\n\n`
          + `Transcript excerpt:\n${text}`,
      },
    ],
  };

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: controller ? controller.signal : undefined,
    });
    if (!res || !res.ok) return "";
    const data = await res.json();
    return stripTtsUnfriendly(extractSummary(data));
  } catch {
    return "";
  } finally {
    if (timer) clearTimeout(timer);
  }
}

// Build the full intro string. Metadata is always produced; the summary sentence
// is appended only when a transcript is present and the LLM call succeeds. The
// episode/season number and the publish date are deterministic - spoken only
// when the feed supplies them, and never dependent on the LLM.
async function buildAnnouncementText({
  show, title, transcript, llm,
  published, episodeNumber, seasonNumber,
} = {}) {
  const cleanShow = sanitise(show);
  const cleanTitle = sanitise(title);
  const episodeClause = formatEpisodeClause(episodeNumber, seasonNumber);
  const spokenDate = formatSpokenDate(published);

  const parts = [];
  if (cleanShow) parts.push(`This is ${cleanShow}.`);
  // "Episode {N}." / "Season {S}, episode {N}." sits between the show and the
  // title, omitted entirely when the feed has no episode number.
  if (episodeClause) parts.push(episodeClause);
  // Only add a full stop when the title does not already end in terminal
  // punctuation, so a title like "Who Won?" does not become "Who Won?.".
  if (cleanTitle) parts.push(/[.!?]$/.test(cleanTitle) ? cleanTitle : `${cleanTitle}.`);
  // "Published on the {Nth of Month YYYY}." follows the title, omitted when the
  // date is missing or unparseable.
  if (spokenDate) parts.push(`Published on ${spokenDate}.`);
  let metadata = parts.join(" ");

  let summary = "";
  if (transcript && llm && typeof llm.fetch === "function") {
    summary = await summariseTranscript({ show: cleanShow, title: cleanTitle, transcript, ...llm });
  }

  let full = metadata;
  if (summary) {
    // Strip any trailing punctuation/whitespace so we never double up the stop.
    const sentenceBody = summary.replace(/[\s.!?]+$/, "");
    // The model is asked for a bare topic phrase to slot into "This episode is
    // about ...". When it instead returns a full sentence that already opens
    // with "This episode" / "In this episode" / "Today" / "The episode", using
    // the lead-in would stutter ("...is about This episode investigates..."), so
    // we drop the lead-in and use the model's sentence as-is.
    const alreadyAClause = /^((in|on)\s+)?(this|today'?s?|the)\s+(episode|podcast|show|week|conversation)\b/i.test(sentenceBody)
      || /^today\b/i.test(sentenceBody);
    if (alreadyAClause) {
      const standalone = sentenceBody.charAt(0).toUpperCase() + sentenceBody.slice(1);
      full = `${metadata} ${standalone}.`.trim();
    } else {
      full = `${metadata} This episode is about ${sentenceBody}.`.trim();
    }
  }

  full = stripTtsUnfriendly(full);
  return full;
}

module.exports = {
  buildAnnouncementText,
  summariseTranscript,
  extractSummary,
  stripTtsUnfriendly,
  sanitise,
  transcriptToText,
  ordinal,
  formatSpokenDate,
  formatEpisodeClause,
  LMSTUDIO_URL,
  LMSTUDIO_MODEL,
  SUMMARY_SCHEMA,
};
